//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.productstocks = new HashSet<productstock>();
        }
    
        public int catid { get; set; }
        public string catname { get; set; }
    
        public virtual ICollection<productstock> productstocks { get; set; }
    }
}
