//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeschedule
    {
        public int scheduleid { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> shopid { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual shop shop { get; set; }
    }
}
