//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderitem
    {
        public orderitem()
        {
            this.damageditems = new HashSet<damageditem>();
        }
    
        public int itemid { get; set; }
        public Nullable<int> productcode { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> shoporderid { get; set; }
    
        public virtual ICollection<damageditem> damageditems { get; set; }
        public virtual shoporder shoporder { get; set; }
    }
}
