//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productdetail
    {
        public productdetail()
        {
            this.damageditems = new HashSet<damageditem>();
        }
    
        public int productid { get; set; }
        public Nullable<int> productcode { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> manufacturing_date { get; set; }
        public Nullable<int> product_stock_id { get; set; }
    
        public virtual ICollection<damageditem> damageditems { get; set; }
    }
}
