//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productstock
    {
        public int productstockid { get; set; }
        public Nullable<int> catid { get; set; }
        public string discription { get; set; }
        public string picture { get; set; }
        public Nullable<int> stockquantity { get; set; }
        public string pname { get; set; }
    
        public virtual category category { get; set; }
    }
}
