//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoporder
    {
        public shoporder()
        {
            this.orderitems = new HashSet<orderitem>();
        }
    
        public int shoporderid { get; set; }
        public int shopid { get; set; }
        public System.DateTime date { get; set; }
        public int total_amount { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
    
        public virtual ICollection<orderitem> orderitems { get; set; }
        public virtual shop shop { get; set; }
    }
}
